spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storeDB?useSSL=false
    username: root
    password: Dogeegscrew2002@

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  #JPA Settings
  jpa.hibernate.ddl-auto: update